### ISSUE TITLE
GetRepositoryIndexes with ignoreSignatures=true does nothing

### ISSUE THREAD

**Issue by djcass44** [chainguard-dev/go-apk#118]
When calling `GetRepositoryIndexes` and disabling signature checking:

```go
indexes, err := apk.GetRepositoryIndexes(ctx, repositories, keys, "x86_64", apk.WithIgnoreSignatures(true))
```

the function will never return any indexes. 

In the `index.go` file, the indexes list is only ever appended to if signature validation is enabled and completes successfully (see [here](https://github.com/chainguard-dev/go-apk/blob/main/pkg/apk/index.go#L218)). This means that when signature validation is disabled, the indexes list will never be appended to and makes this entire function essentially a no-op.

I'm happy to open an MR to fix it if needed.

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/chainguard-dev/go-apk/pull/121

Thanks!
