### ISSUE TITLE
Providing packages in world with constraints is not respected in existing list

### ISSUE THREAD

**Issue by deitch** [chainguard-dev/go-apk#59]
Consider the following list of packages:

```yaml
packages:
- git
```

`git` depends on `libcurl`, which depends on `libcrypto`, which depends on `openssl-config`. So the final graph should have `openssl-config` in it, at the highest version. Let's say that we have `openssl-config` at the highest version of `3.2`.

This works fine.

Now consider this list:

```yaml
packages:
- git
- openssl-config-special
```

where `openssl-config-special` provides `openssl-config=3.1.0-r0`, i.e. _below_ the highest available, which, as described above, is `3.2`. Because we explicitly provide `openssl-config-special`, we should take that one to satisfy git's `openssl-config` dependency, and not the regular one, which would be at `3.2`. This, too, works.

Now provide our special version with a constraint.

```yaml
packages:
- git
- openssl-config-special=3.1.0
```

Now, it fails. It _will_ include `openssl-config-special=3.1.0` in the final graph, but it _also_ will include `openssl-config=3.2.0`.

The reason for this is because the map that contains the list of "existing dependencies" did not separate name from version _before_ tracking, only _after_.

This was fixed in #55 , where we not only added the parent, but to do so, we ensured that the tracking list is by name.

This issue is mainly as a tracking issue, so we can know it in the past, as well as for us to add a test.

**Comment by mattmoor** [comment]
Pulling the latest go-apk into tf-apko also reveals a test breakage that may very well be related to this.

We fixate a list of packages that includes wolfi-baselayout pinned to r0, and we get back r3 😞

I haven’t tried bisecting the change from go-apk that broke this, but this seems back and we should definitely get to the bottom and add a bunch of tests for this stuff.

cc @imjasonh

**Comment by deitch** [comment]
@mattmoor don't worry about figuring out which change; I can get to that. 

Can you post here a precise reproduction of the call you make, expected output, and actual? Is it just the r0 -> r3? How is the function called and with what parameters?

**Comment by mattmoor** [comment]
I was just reproducing this with `apko` and your PR to update `apko`:
```yaml
contents:
  repositories:
  - https://packages.wolfi.dev/os
  keyring:
  - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
  - wolfi-baselayout=20230201-r0
  - ca-certificates-bundle=20230506-r0
  - glibc-locale-posix=2.37-r6
  - ko=0.13.0-r3
  - tzdata=2023c-r0

archs:
- x86_64
```

At HEAD (note two versions of `wolfi-baselayout`):
```
go run . show-packages foo.yaml
amd64
  ca-certificates-bundle 20230506-r0
  glibc-locale-posix 2.37-r6
  wolfi-baselayout 20230201-r3
  ld-linux 2.37-r7
  ko 0.13.0-r3
  tzdata 2023c-r0
  wolfi-baselayout 20230201-r0
```

With your latest change:
```
go run . show-packages foo.yaml
amd64
ca-certificates-bundle 20230506-r0
glibc-locale-posix 2.37-r6
wolfi-baselayout 20230201-r3
ld-linux 2.37-r7
ko 0.13.0-r3
tzdata 2023c-r0
```

@kaniini fed these initial constraints through `apk fix` earlier, which was a neat trick and it thought the solution should be `wolfi-baselayout=20230201-r0` (not `-r3`, which we get now).

**Comment by deitch** [comment]
That's solid. We can work with that.

**Comment by deitch** [comment]
I know why this is. We got lucky with the `openssl-config` case, because of alphabetical ordering made the top-level package already in place. We shouldn't depend on that. Getting a fix in place.

**Comment by deitch** [comment]
See #60

**Comment by mattmoor** [comment]
cc @imjasonh FYI

**Comment by deitch** [comment]
I am glad we pushed for the tests on this. It highlighted some issues that we managed to test and resolved, in addition to the just plain goodness of having the tests.

**Comment by mattmoor** [comment]
I've confirmed that #60 fixes the tf-apko issue.  I'm going to test the fips issue next 🤞

**Comment by mattmoor** [comment]
I've confirmed that the fips issue is fixed as well.

**Comment by deitch** [comment]
Excellent. So let's get #60 in, I can update the PR on apko to include it, and we will be good.
