### ISSUE TITLE
http scheme for repository is not supported

### ISSUE THREAD

**Issue by aohoyd** [chainguard-dev/go-apk#91]
Hi! I'm trying to adopt melange and apko for our build processes and found an issue which stops me from that. It is not currently possible to use apk repository with `http` scheme, index just ignored.

I found that `http` is ignored in https://github.com/chainguard-dev/go-apk/blob/36d0bc2cdc194fbabf5715c2404f5e5bdab4ca62/pkg/apk/index.go#L97, is it by design? I'm going to submit PR but not sure that you'll accept it because of insecure scheme:) Is it ok to also use insecure channel?

**Comment by Elizafox** [comment]
Discussing this with other engineers at the company, I don't think we want to support non-HTTP repos. If someone says otherwise I will reopen this.
